---
- name: Adding disks for VM {{ item.name }} to NetBox
  netbox.netbox.netbox_virtual_disk:
    netbox_url: "{{ netbox_url }}"
    netbox_token: "{{ netbox_token }}"
    data:
      size: "{{ disk.size }}"
      name: "{{ disk.name }}"
      virtual_machine: "{{ item.name }}"
  with_items: "{{ item.config | pve_parse_disks }}"
  loop_control:
    loop_var: disk

