---
- name: Generating TAG list. Will be prefixed by
  set_fact:
    pve_tags: "{{ pve_tags | default([]) + ( tags.item_vm.config.tags | default('') | split(';') ) }}"
  with_items: "{{ proxmox_agents.results }}"
  loop_control:
    loop_var: tags
  when: proxmox_agents is defined
  delegate_to: localhost

- name: Creating Tags in NetBox
  debug:
    msg: "Creating TAG: {{ item }}"
  with_items: "{{ pve_tags | unique }}"
  when: item != ''

- name: Adding VMs to NetBox
  debug:
    msg: "Name: {{ vm.item_vm.config.name }} - Memory: {{ vm.item_vm.config.memory }} - VCPUs: {{ vm.item_vm.config.cores * (vm.item_vm.config.sockets | default(1)) }} - Tags: {{ vm.item_vm.config.tags | default ('') | split(';')  }}"
  with_items: "{{ proxmox_agents.results }}"
  loop_control:
    loop_var: vm
  when: proxmox_agents is defined

#- name: Debug
#  debug:
#    msg: "{{ proxmox_agents }}"
#  when: proxmox_agents is defined
