---
- include_tasks: get_vm_agent_data.yml
  vars:
    name: "{{ cluster.name }}"
    api_host: "{{ cluster.api_host }}"
    api_user: "{{ cluster.api_user }}"
    api_token: "{{ cluster.api_token }}"
    api_secret: "{{ cluster.api_secret }}"
  with_items: "{{ proxmox_clusters }}"
  loop_control:
    loop_var: cluster

- include_tasks: create_vm_in_netbox.yml
 
