---
- include_tasks: sync_to_netbox.yml
  vars:
    cluster_name: "{{ cluster.cluster_name }}"
    api_host: "{{ cluster.api_host }}"
    api_user: "{{ cluster.api_user }}"
    api_token: "{{ cluster.api_token }}"
    api_secret: "{{ cluster.api_secret }}"
  with_items: "{{ proxmox_clusters }}"
  loop_control:
    loop_var: cluster

